# Generated by Django 3.0.5 on 2020-04-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200422_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
