# Generated by Django 3.0.5 on 2020-04-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200414_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Student', 'Student')], default='Student', max_length=9),
        ),
    ]
