# Generated by Django 3.0.5 on 2020-04-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_userprofileinfo_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
